### PR TITLE
Audience single string claim data type retention when copying

### LINKED ISSUE #890: A single audience value gets converted into a set with one entry
**Describe the bug**

In the scenario when we first build claims with `DefaultClaimsBuilder` and then pass them to `JwtBuilder`, a single audience value gets converted somewhere on the way from `String` to `Set<String>`. **This is a breaking change for the APIs, which expect a string audience value.**

**To Reproduce**
1. Build claims:
```java
var claims = new DefaultClaimsBuilder().audience().single("https://login.salesforce.com").build();
```
2. Check the type of the claim value of in Debugger (must be `String`):
image
3. Create a JWT builder with the claims object:
```java
var jwtBuilder = Jwts.builder().claims(claims);
```
4. Check again the type of the claim value in Debugger (see `jwtBuilder`; this time it's `Set<String>`):
image

**Expected behavior**
In case of using `audience().single(...)` the type of the `audience` claim should stay `String` after calling `claims(...)` on the JWT builder.

**Workaround**
Note, if setting the claim directly on the JWT builder, the type is preserved:
```java
var jwtBuilder = Jwts.builder().audience().single("https://login.salesforce.com");
```

### PR DESCRIPTION
**Pull request by lhazlewood**
Ensured a single string `aud` (Audience) claim would be retained (without converting it to a `Set`) when copying/applying a source Claims instance to a destination Claims builder.

Updated CHANGELOG.md accordingly.

Fixes #890.

### CODE REVIEW

File: impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy [hunk 1]
```diff
@@ -1167,6 +1168,36 @@ class JwtsTest {
...
+        int i = jws.indexOf('.')
+        int j = jws.lastIndexOf('.')
+        def b64 = jws.substring(i, j)
+        def json = Strings.utf8(Decoders.BASE64URL.decode(b64))
+        def deser = Services.loadFirst(Deserializer)
+        def m = deser.deserialize(new StringReader(json)) as Map<String,?>
+
+        assertEquals aud, m.get('aud') // single string value
+    }
+
```
Comment (lhazlewood) [inline impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy:1200]: @devdanylo and @arvindkrishnakumar-okta

Please feel free to take a look at this PR and the test case immediately above, especially lines 1184, 1185 and 1198.

Tests pass locally, I'm just waiting for CI to verify.

**Comment by lhazlewood** [comment]
CI passed successfully, merging.

File: impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy (hunk 1 above)
Comment (arvindkrishnakumar-okta) [reply impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy:1200]: LGTM, thanks for the quick response!

Comment (devdanylo) [reply impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy:1200]: Thank you   🤝
